### ISSUE TITLE
Android4: s planner: Describe error

### ISSUE THREAD

**Issue by a-x-** [vladmos/holidays#1]
![screenshot_2015-09-11-22-36-23](https://cloud.githubusercontent.com/assets/6201068/9824573/5e7b1bd6-58d6-11e5-87e4-768f2603471b.png)

**Comment by vladmos** [comment]
Как это воспроизвести?

Гугл говорит, что такая ошибка возникает при попытке поставить приложение, а эти файлы надо использовать непосредственно в календаре. Можно подключить поток по http, ссылки тут: http://vladmos.github.io/holidays/ .
